{{ if eq .Values.global.env.name "qa" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web.fullname" . }}-qa-configmap
data:
  ASPNETCORE_ENVIRONMENT: "Staging"
  production: "false"
  staging: "true"
  dev: "false"
  mainAppApiUrl: "https://{{ .Values.global.domains.api }}"
  createAccountRedirectUrl: "https://{{ .Values.global.domains.web }}/create-user-callback"
  geoserverMapServiceUrl: "https://{{ .Values.global.domains.geoserver }}/geoserver/OCStormwater"
  ocStormwaterToolsBaseUrl: "https://{{ .Values.global.domains.webmvc }}"
  auth0_domain: "ocstormwatertools.us.auth0.com"
  auth0_clientId: "ifBEaIsDKHXBQoIyDVl1CB21avZh1xEx"
  auth0_redirectUri: "https://qa-web.ocstormwatertools.org"
  auth0_audience: "OCSTApi"
{{ end }}