{{ if eq .Values.global.env.name "qa" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web.fullname" . }}-qa-configmap
data:
  ASPNETCORE_ENVIRONMENT: "Staging"
  production: "false"
  staging: "true"
  dev: "false"
{{ end }}